# Generated by Django 5.2 on 2025-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='mascotas/')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
