# Generated by Django 5.2 on 2025-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mascota_descripcion_alter_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
