# Generated by Django 5.1.7 on 2025-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mascota_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=50)),
                ('youtubeUrl', models.URLField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
